name: asignmet4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter_bloc: ^8.1.4
  image_picker: ^1.0.7
  flutter:
    sdk: flutter
  http: ^1.2.0
  simple_animations: ^5.0.2
  curved_navigation_bar: ^1.0.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
 
  assets:
    
    - image/