name: api_lab
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  card_swiper: ^3.0.1
  lottie: ^3.1.0
  get_it: ^7.6.7
  image_picker: ^1.0.7
  flip_card: ^0.7.0
  flutter_bloc: ^8.1.4
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
